# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unknown.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1064, 884)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 80, 471, 191))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.a0 = QtWidgets.QPushButton(self.centralwidget)
        self.a0.setGeometry(QtCore.QRect(80, 330, 231, 141))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.a0.setFont(font)
        self.a0.setObjectName("a0")
        self.a1 = QtWidgets.QPushButton(self.centralwidget)
        self.a1.setGeometry(QtCore.QRect(400, 330, 231, 141))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.a1.setFont(font)
        self.a1.setObjectName("a1")
        self.a2 = QtWidgets.QPushButton(self.centralwidget)
        self.a2.setGeometry(QtCore.QRect(730, 330, 231, 141))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.a2.setFont(font)
        self.a2.setObjectName("a2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1064, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "請問您是？"))
        self.a0.setText(_translate("MainWindow", "住戶"))
        self.a1.setText(_translate("MainWindow", "快遞"))
        self.a2.setText(_translate("MainWindow", "訪客"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
